### ISSUE TITLE
where can I find or generate pkiclient.exe for SCEP service on fedora?

### ISSUE THREAD

**Issue by cgx-avenue** [dogtagpki/pki#3386]
Package:
pki-10.10

Environment:
Fedora 33

Description:
I'm setting up SCEP following https://www.dogtagpki.org/wiki/SCEP_Setup.  Everything goes fine until the last sector:
The SCEP service can be accessed at http://server.example.com:8080/ca/cgi-bin/pkiclient.exe. Other web UI services are working fine.
I checked the path /usr/share/pki/ca and even cannot find any pkiclient.exe file on my fedora. 
Did I miss something or anything not correct?

**Comment by SilleBille** [comment]
I don't think we package/generate .exe any more. The wiki page may need to be updated.

**Comment by abotelho-cbn** [comment]
> I don't think we package/generate .exe any more. The wiki page may need to be updated. Maybe try to setup SCEP by following this doc? https://access.redhat.com/documentation/en-us/red_hat_certificate_system/10/html-single/administration_guide/index#Enrolling_a_Certificate_in_a_Cisco_Router

The documentation you are referring to includes pkiclient.exe in the url to use.

```scep(config)# crypto ca trusted-root1
scep(ca-root)# root CEP http://server.example.com:8080/ca/cgi-bin/pkiclient.exe
scep(ca-root)# crl optional
scep(ca-root)# exit
scep(config)# cry ca authenticate 1
scep(config)# crypto ca trusted-root0
scep(ca-root)# root CEP http://server.example.com:8080/ca/cgi-bin/pkiclient.exe
scep(ca-root)# crl optional
scep(ca-root)# exit
scep(config)# cry ca authenticate 0```

**Comment by abotelho-cbn** [comment]
> 

What error are you getting back when performing on the specified SCEP URL?
