### ISSUE TITLE
pki fails to start if empty dir /var/lib/pki/pki-tomcat/kra exists

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#3397]
If an empty directory /var/lib/pki/pki-tomcat/kra is present on the filesystem, pki fails to start.

On fedora 32 with pki-server (10.10.0-2.fc32) :
```
# mkdir /var/lib/pki/pki-tomcat/kra
# systemctl restart pki-tomcatd@pki-tomcat
Job for pki-tomcatd@pki-tomcat.service failed because the control process exited with error code.
See "systemctl status pki-tomcatd@pki-tomcat.service" and "journalctl -xe" for details.
```
and the journal shows:
```
systemd[1]: Starting PKI Tomcat Server pki-tomcat...
pki-server[7658]: ERROR: [Errno 2] No such file or directory: '/var/lib/pki/pki-tomcat/kra/conf/CS.cfg'
systemd[1]: pki-tomcatd@pki-tomcat.service: Control process exited, code=exited, status=1/FAILURE
systemd[1]: pki-tomcatd@pki-tomcat.service: Failed with result 'exit-code'.
systemd[1]: Failed to start PKI Tomcat Server pki-tomcat.
```

pki should gracefully handle this situation and either consider kra not enabled or not installed.

**Comment by edewata** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1904112

**Comment by flo-renaud** [comment]
For full ref, I tried on different OSes with the following versions:
OS | pki version | restart pki with empty dir /var/lib/pki/pki-tomcat/kra
-- | -- | --
Fedora 27 | 10.5.12-1 | fails
Fedora 32 | 10.10.0-2 | fails
Fedora 33 | 10.10.0-2 | fails
Fedora 33 + nightly copr | 10.11.0-0.1.alpha1.20210111225601UTC.d25ef1e7 | fails
RHEL 7.8 | 10.5.17-6 | fails
RHEL 7.9 | 10.5.18-8 | fails
RHEL 8.3 | 10.9.4-1 | succeeds
RHEL 8.4 | 10.10.2-1 | succeeds
