### ISSUE TITLE
acme: resubmitting challenge leads to `java.lang.Exception: Challenge is already valid`

### ISSUE THREAD

**Issue by zdzichu** [dogtagpki/pki#3462]
Hi,

  I'm trying to use ACME component included in `freeipa-server-4.9.1-1.fc33.x86_64` and `pki-acme-10.10.4-1.20210212013442UTC.22ab633b.fc33` with Fedora 33. As a client, I'm using `cert-manager 1.2.0` deployed on Kubernetes cluster. I'm aware you mainly test with `certbot`, but https://github.com/jetstack/cert-manager is widely recommended as THE solution for ACME on k8s.

It looks like cert-manager retries few times, triggering an exception in ACME code in Dogtag. I've looked at the code and I wonder, if dogtag could just log & continue when receiving already validated challenge?  Is there a point in throwing an exception?

Debug log attached.
[debug.2021-02-16.log](https://github.com/dogtagpki/pki/files/6002166/debug.2021-02-16.log)

**Comment by frasertweedale** [comment]
Thank you for the detailed issue report.

Dogtag can and should handle this scenario better.  In particular, `ACMEChallengeService.handlePOST` should retry the challenge if state is "invalid" and can safely "do nothing" when state is "processing" or "invalid".  (For "processing" state, it might be best to reset counters/timers or restart the validation thread).

BUT, this is also a bug in cert-manager.  Its behaviour deviates substantially from RFC 8555.  In particular, https://tools.ietf.org/html/rfc8555#section-7.5.1 states:

```
   Usually, the validation process will take some time, so the client
   will need to poll the authorization resource to see when it is
   finalized.  For challenges where the client can tell when the server
   has validated the challenge (e.g., by seeing an HTTP or DNS request
   from the server), the client SHOULD NOT begin polling until it has
   seen the validation request from the server.

   To check on the status of an authorization, the client sends a POST-
   as-GET request to the authorization URL, and the server responds with
   the current authorization object.  In responding to poll requests
   while the validation is still in progress, the server MUST return a
   200 (OK) response and MAY include a Retry-After header field to
   suggest a polling interval to the client.
```

Instead of polling the **authorization** resource as specified by RFC 8555, cert-manager is re-POSTing the challenge response.  Therefore please also raise a ticket against cert-manager, if you have not done so already.

**Comment by zdzichu** [comment]
Unfortunately it wasn't fully fixed. Dogtag still throws 500 errors on various occasions, like:
```2021-08-01 00:06:18 [ajp-nio-127.0.0.1-8009-exec-10] SEVERE: Servlet.service() for servlet [ACME] in context with path [/acme] threw exception
org.jboss.resteasy.spi.UnhandledException: java.lang.Exception: Invalid nonce: MqMOKakqfg4BjbqiVA_4wg
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:78)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:179)
[…]
Caused by: java.lang.Exception: Invalid nonce: MqMOKakqfg4BjbqiVA_4wg
        at org.dogtagpki.acme.server.ACMEEngine.validateNonce(ACMEEngine.java:628)
        at org.dogtagpki.acme.server.ACMEOrderService.handlePOST(ACMEOrderService.java:50)
        at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
```

At the cert-manager side (https://github.com/jetstack/cert-manager/issues/3777) they don't really see non-compliant behaviour. Could I ask @rcritten or @edewata to share some comments on cert-manager's issue?
