### ISSUE TITLE
CRMF requests with extensions other than SKID cannot be processed

### ISSUE THREAD

**Issue by carl-wallace** [dogtagpki/pki#3497]
See https://github.com/dogtagpki/pki/blob/v10.5.18/base/server/cms/src/com/netscape/cms/profile/common/EnrollProfile.java#L2289

That line should read:

ext = new Extension(oid, isCritical, extValue);

**Comment by carl-wallace** [comment]
Fixed here: https://github.com/dogtagpki/pki/pull/3498/commits/3d3086cf904378dfc4dd0dceff2037633b2d4ec5

**Comment by SilleBille** [comment]
Fixed via https://github.com/dogtagpki/pki/pull/3498 . Closing this issue
