### ISSUE TITLE
Remove dependency on resteasy-atom-provider

### ISSUE THREAD

**Issue by edewata** [dogtagpki/pki#3516]
Currently PKI depends on `resteasy-atom-provider` to provide the `Link` class which is used to store links to REST resources, for example:
https://github.com/dogtagpki/pki/blob/master/base/common/src/main/java/com/netscape/certsrv/user/UserData.java#L64
https://github.com/dogtagpki/pki/blob/master/base/common/src/main/java/com/netscape/certsrv/base/DataCollection.java#L35

The links turn out to be not very useful, so it can be removed to reduce the size of REST messages and also reduce the number of PKI dependencies.

The ultimate goal is to remove these lines:
https://github.com/dogtagpki/pki/blob/master/.classpath#L50
https://github.com/dogtagpki/pki/blob/master/pki.spec#L203
https://github.com/dogtagpki/pki/blob/master/pki.spec#L436
https://github.com/dogtagpki/pki/blob/master/pom.xml#L158-L164

**Comment by ckelleyRH** [comment]
@edewata sure, I've taken a look and I think the only snag is the link being required in this method: https://github.com/dogtagpki/pki/blob/400fbaec79150d65c573d82e5bea4ed18886f518/base/server/src/main/java/com/netscape/cms/servlet/base/PKIService.java#L166

**Comment by edewata** [comment]
Yeah, I think we can move the `URI` creation from where the `setLink()` was called:
https://github.com/dogtagpki/pki/blob/master/base/server/src/main/java/org/dogtagpki/server/rest/UserService.java#L104
to where the `getLink()` was called:
https://github.com/dogtagpki/pki/blob/master/base/server/src/main/java/org/dogtagpki/server/rest/UserService.java#L390

**Comment by ckelleyRH** [comment]
Ah, good point, this is much better than what I tried to do! I've pushed a new set of commits with that suggestion incorporated.
