### ISSUE TITLE
Deprecate/drop XML REST API

### ISSUE THREAD

**Issue by edewata** [dogtagpki/pki#3553]
Currently PKI uses XML message format in REST API by default, and supports JSON as an optional format. Supporting XML in Fedora requires maintaining a number of packages (e.g. JAXB) which takes away development resources. To reduce the dependencies, the default message format should be changed to JSON in PKI 10.11 (if there's enough time) or PKI 10.12, and XML should become optional. Then in PKI 11 XML should be deprecated/dropped, and JSON will become the only supported format.

The task should be done in several steps:

* Issue #3558: Test and document JSON REST API
* Issue #3567: Add missing JSON mappers
* Issue #3606: Remove XML mappers
* Update all clients and tools (e.g. PKI CLI, web UI, IPA) to use JSON
* Generate deprecation warning for XML REST API in PKI 10
* Drop XML REST API in PKI 11
* Drop JAXB dependency in PKI 11

**Comment by edewata** [comment]
@ckelleyRH Do you want to take a stab at this?

**Comment by ckelleyRH** [comment]
Probably a good learning exercise, get to fire up all the different parts and poke them to see what they do :+1:

**Comment by edewata** [comment]
Thanks! Let me know if you have any questions! I'll probably help on this one too.

**Comment by ckelleyRH** [comment]
Great, I'll have a go and get back to you if I break something :-D

**Comment by edewata** [comment]
@rcritten @frasertweedale Just a heads up.

**Comment by rcritten** [comment]
It would be nice to go XML-free. Will a request fail in a predictable way if XML is not supported so the client (dogtag, IPA, whatever) can fall back to JSON?

**Comment by ckelleyRH** [comment]
@rcritten I forced one of the REST calls to accept `JSON` only:
```
userservice_rest_json ⇧0 ⇩0 >2(+3/-18) ^0(+/-) ckelley@localhost ~/git/pki
curl -k -H "Accept: application/json" --user caadmin:Secret.123 -s https://localhost.localdomain:8443/ca/rest/admin/users
```
```json
{
    "total": 3,
    "entries": [
        {
            "id": "CA-localhost.localdomain-8443",
            "UserID": "CA-localhost.localdomain-8443",
            "FullName": "CA-localhost.localdomain-8443",
            "Link": {
                "rel": "self",
                "href": "https://localhost.localdomain:8443/ca/rest/admin/users/CA-localhost.localdomain-8443",
                "type": "application/xml"
            },
            "Attributes": {
                "Attribute": []
            }
        },
        {
            "id": "caadmin",
            "UserID": "caadmin",
            "FullName": "caadmin",
            "Link": {
                "rel": "self",
                "href": "https://localhost.localdomain:8443/ca/rest/admin/users/caadmin",
                "type": "application/xml"
            },
            "Attributes": {
                "Attribute": []
            }
        },
        {
            "id": "pkidbuser",
            "UserID": "pkidbuser",
            "FullName": "pkidbuser",
            "Link": {
                "rel": "self",
                "href": "https://localhost.localdomain:8443/ca/rest/admin/users/pkidbuser",
                "type": "application/xml"
            },
            "Attributes": {
            }
        }
                "Attribute": []
            }
        }
    ],
    "Link": []
}
```

and attempting to get `XML`:

```
userservice_rest_json ⇧0 ⇩0 >2(+3/-18) ^0(+/-) ckelley@localhost ~/git/pki
curl -k -H -I "Accept: application/xml" --user caadmin:Secret.123 -s 
https://localhost.localdomain:8443/ca/rest/admin/users
Could not find MessageBodyWriter for response object of type: com.netscape.certsrv.user.UserCollection of media type: application/xml;charset=UTF-8
```
...so it should be clear to the caller that `XML` is not supported. It doesn't tell you what _is_ supported, but I would imagine most people would reach for `JSON` if they couldn't get `XML`. 

Interestingly, at least to me, if you omit the `-H` parameter completely then `curl` appears to default to `XML`, which could cause a few issues for people who are not currently specifying a response type in the header.

**Comment by edewata** [comment]
I moved the testing/documentation task to #3558, so this ticket will become the epic.
