### ISSUE TITLE
end entity -> retrieval -> list certificates is broken

### ISSUE THREAD

**Issue by mharmsen99** [dogtagpki/pki#3628]
The following issue was reported by awnuk@purestorage.com:

EE certificate list works with the following RPMs:

    rpm -qa | grep 'pki\|389'

    389-ds-base-libs-1.3.10.2-8.el7_9.x86_64

    pki-ca-10.5.18-7.el7.noarch

    389-ds-base-1.3.10.2-8.el7_9.x86_64

    pki-base-10.5.18-7.el7.noarch

    pki-base-java-10.5.18-7.el7.noarch

    pki-server-10.5.18-7.el7.noarch

    dogtag-pki-server-theme-10.5.18-7.el7.noarch

    pki-tools-10.5.18-7.el7.x86_64 

but it is broken with the following RPMs: 

    pki-ca-10.5.18-12.el7_9.noarch

    pki-base-10.5.18-12.el7_9.noarch

    pki-base-java-10.5.18-12.el7_9.noarch

    pki-server-10.5.18-12.el7_9.noarch

    389-ds-base-1.3.10.2-10.el7_9.x86_64

    dogtag-pki-server-theme-10.5.18-12.el7.noarch

    pki-tools-10.5.18-12.el7_9.x86_64
    389-ds-base-libs-1.3.10.2-10.el7_9.x86_64

and it is also broken with the following RPMs:

    rpm -qa | grep 'pki\|389'

    pki-base-10.5.18-14.el7_9.noarch

    pki-server-10.5.18-14.el7_9.noarch

    pki-tools-10.5.18-14.el7_9.x86_64

    389-ds-base-libs-1.3.10.2-12.el7_9.x86_64

    pki-base-java-10.5.18-14.el7_9.noarch

    dogtag-pki-server-theme-10.5.18-14.el7.noarch

    389-ds-base-1.3.10.2-12.el7_9.x86_64
    pki-ca-10.5.18-14.el7_9.noarch

End entity certificate list result page when it is broken, displays two sets of paging buttons aligned to the left instead of a single set that is centered.
Dual set of paging buttons doesn't provide usual paging functionality.
![Screen Shot 2021-06-29 at 3 29 20 PM](https://user-images.githubusercontent.com/25108793/124201297-ea8c2480-da94-11eb-969a-875b8db2beba.png)

**Comment by ckelleyRH** [comment]
This issue has been resolved in all versions.
