### ISSUE TITLE
Replace JAXB with DOM

### ISSUE THREAD

**Issue by edewata** [dogtagpki/pki#3693]
Removing XML mappers (PR #3606) requires coordination with IPA, which could take some time to complete. As an intermediary step we can replace JAXB with DOM (so we can remove JAXB dependency), but maintain the XML mapping for now. Here are the classes that need to be converted:

- [x] Account (edewata) #3690
- [x] CertDataInfo (edewata) #3692 
- [x] CertData (edewata) #3694
- [x] CertEnrollmentRequest (cdorney) #3711 
- [x] CertRetrievalRequest (edewata) #3696
- [x] CertRevokeRequest (edewata) #3697
- [x] CertReviewResponse (edewata) #3715
- [x] CertSearchRequest (edewata) #3703
- [x] CMSRequestInfo (edewata) #3714
- [x] PolicyConstraint (ckelley) #3695 
- [x] PolicyConstraintValue (ckelley) #3695 
- [x] PolicyDefault (ckelley) #3705
- [x] ProfileAttribute (ckelley) #3704
- [x] ProfileData (ckelley) #3716
- [x] ProfileDataInfo (ckelley) #3698
- [x] ProfileDataInfos (ckelley) #3699
- [x] ProfileInput (cdorney) #3707
- [x] ProfileOutput (ckelley) #3706
- [x] ProfileParameter (ckelley) #3704
- [x] ProfilePolicy (ckelley) #3708
- [x] ProfilePolicySet - Nothing to do, holds a collection of `ProfilePolicy`
- [x] PKIException and ResourceMessage (edewata) #3709

**Comment by ckelleyRH** [comment]
@edewata I'm working on `PolicyContraint{Value}`, I'm rebasing on top of the work you've already done so far.

**Comment by ckelleyRH** [comment]
Also FYI, I noticed running the tests that with the new DOM-based XML the `standalone` directive is `no` (this is by default). We must have been asking jaxb to give us `yes`, so there is a difference in marshalling between what we are implementing now and what is already in place:
```
## OLD ##
XML (before): <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<policyConstraintValue id="foo">
    <descriptor>
        <mSyntax>choice</mSyntax>
        <mConstraint>true,false,-</mConstraint>
        <mDescription>CMS_PROFILE_CRITICAL</mDescription>
        <mDef>-</mDef>
    </descriptor>
    <value>bar</value>
</policyConstraintValue>

## NEW ##
XML (before): <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<policyConstraintValue id="foo">
    <descriptor>
        <mSyntax>choice</mSyntax>
        <mConstraint>true,false,-</mConstraint>
        <mDescription>CMS_PROFILE_CRITICAL</mDescription>
        <mDef>-</mDef>
    </descriptor>
    <value>bar</value>
</policyConstraintValue>
```

**Comment by edewata** [comment]
Yeah, I noticed that too, but I'm not sure how to fix it, and it doesn't seem to cause any issue so far. Do you see any potential issue?

**Comment by edewata** [comment]
`ʅ(́◡◝)ʃ` beats me.. I guess it's OK since it's only used for validation, and hopefully we can drop it completely soon.

**Comment by ckelleyRH** [comment]
Yeah it's only transient code but good to know where to start looking if it does go wrong.

**Comment by ckelleyRH** [comment]
I'm beginning to worry that the majority of the remaining classes are linked together in a spider web of pain.

**Comment by edewata** [comment]
It looks like so far we're only using DOM for marshalling & unmarshalling XML responses, but for XML requests we're still relying on JAXB. That's probably why we can't remove JAXB yet in some cases. I'm investigating how to use DOM for XML requests. I think we probably should add the DOM mapping now, then drop JAXB once I figure this out .

**Comment by ckelleyRH** [comment]
OK, I'll continue with mapping-adding, thanks for looking into it!

**Comment by ckelleyRH** [comment]
All done, cheers @c-dorney @edewata!
