### ISSUE TITLE
IPA: failure to install replica with external CA (using @pki/master copr repo)

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#3974]
The IPA nightly tests using the @pki/master copr repo are failing when installing a replica with external CA.

Test scenario:
- install IPA server with external CA: `ipa-server-install --domain ipa.test --realm IPA.TEST --external-ca -a Secret123 -p Secret123 -U`, sign /root/ipa.csr by an external CA, `ipa-server-install --domain ipa.test --realm IPA.TEST --external-cert-file /path/to/chain.crt -a Secret123 -p Secret123 -U`
- install IPA replica with CA service: `ipa-client-install --domain ipa.test --realm IPA.TEST --principal admin --password Secret123 -U; kinit admin; ipa-replica-install --setup-ca`

The replica installation fails in the pkispawn step, with the following stderr:
```
DEBUG: Command: certutil -L -d /etc/pki/pki-tomcat/alias -f /etc/pki/pki-tomcat/pfile -n caSigningCert External CA -a
DEBUG: Cert not found: caSigningCert External CA
INFO: Exporting caSigningCert External CA (0xe2b71c4169293e655d9165358746c979fde2f6c6) from PKCS #12 file
INFO: Java command: /usr/lib/jvm/jre-17-openjdk/bin/java -cp /usr/share/pki/lib/* -Dcom.redhat.fips=false -Djava.util.logging.config.file=/usr/share/pki/etc/logging.properties com.netscape.cmstools.cli.MainCLI -d /etc/pki/pki-tomcat/alias -C /etc/pki/pki-tomcat/pfile --debug pkcs12-cert-export --pkcs12-file /tmp/ca.p12 --pkcs12-password-file /tmp/tmpkj6khp9t/password.txt --cert-file /tmp/tmpgve7l020/ca-cert.pem --cert-id 0xe2b71c4169293e655d9165358746c979fde2f6c6 --debug
INFO: Server URL: https://replica0.ipa.test:8443
INFO: Loading NSS password from /etc/pki/pki-tomcat/pfile
INFO: NSS database: /etc/pki/pki-tomcat/alias
INFO: Message format: null
INFO: Command: pkcs12-cert-export --pkcs12-file /tmp/ca.p12 --pkcs12-password-file /tmp/tmpkj6khp9t/password.txt --cert-file /tmp/tmpgve7l020/ca-cert.pem --cert-id 0xe2b71c4169293e655d9165358746c979fde2f6c6 --debug
INFO: Module: pkcs12
INFO: Module: cert
INFO: Module: export
org.apache.commons.codec.DecoderException: Illegal hexadecimal character x at index 1
    at org.apache.commons.codec.binary.Hex.toDigit(Hex.java:369)
    at org.apache.commons.codec.binary.Hex.decodeHex(Hex.java:109)
    at org.apache.commons.codec.binary.Hex.decodeHex(Hex.java:77)
    at com.netscape.cmstools.pkcs12.PKCS12CertExportCLI.execute(PKCS12CertExportCLI.java:102)
    at org.dogtagpki.cli.CommandCLI.execute(CommandCLI.java:58)
    at org.dogtagpki.cli.CLI.execute(CLI.java:357)
    at org.dogtagpki.cli.CLI.execute(CLI.java:357)
    at org.dogtagpki.cli.CLI.execute(CLI.java:357)
    at com.netscape.cmstools.cli.MainCLI.execute(MainCLI.java:658)
    at com.netscape.cmstools.cli.MainCLI.main(MainCLI.java:696)
ERROR: Command: /usr/lib/jvm/jre-17-openjdk/bin/java -cp /usr/share/pki/lib/* -Dcom.redhat.fips=false -Djava.util.logging.config.file=/usr/share/pki/etc/logging.properties com.netscape.cmstools.cli.MainCLI -d /etc/pki/pki-tomcat/alias -C /etc/pki/pki-tomcat/pfile --debug pkcs12-cert-export --pkcs12-file /tmp/ca.p12 --pkcs12-password-file /tmp/tmpkj6khp9t/password.txt --cert-file /tmp/tmpgve7l020/ca-cert.pem --cert-id 0xe2b71c4169293e655d9165358746c979fde2f6c6 --debug
```

Full logs available in http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ac4bcd0e-b961-11ec-9866-fa163ea04eff/test_integration-test_acme.py-TestACMEwithExternalCA-install/replica0.ipa.test/var/log/

Companion issue logged against IPA: https://pagure.io/freeipa/issue/9139

**Comment by flo-renaud** [comment]
@ckelleyRH thanks for the quick update!

**Comment by edewata** [comment]
I think this particular issue is caused by incorrect cert ID handling, although there's a problem with key ID handling too. I created PR #3975 as a quick fix, but maybe later we want to add a proper code & test for this. A COPR build with this fix should be available here soon (if not already):
https://copr.fedorainfracloud.org/coprs/edewata/pki/builds/
or here after merging the PR:
https://copr.fedorainfracloud.org/coprs/g/pki/master/builds/

**Comment by flo-renaud** [comment]
Hi @edewata 
I did a quick test with your copr repo (dogtag-pki-server-11.2.0-0.1.alpha1.20220411164116UTC.43429165.fc35.noarch) and freeipa from master branch, and the install of a replica with an external CA works well.

**Comment by edewata** [comment]
@flo-renaud Thanks for testing. The PR is merged and the build is available in @pki/master COPR repo. Feel free to reopen if it's still a problem. Thanks!
