### ISSUE TITLE
Nightly test failure in pki-server cert-fix with IPA

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#4012]
FreeIPA nightly tests detect a regression in `pki-server cert-fix` when using pki from the copr repo @pki/master. See PR#[1732](https://github.com/freeipa-pr-ci2/freeipa/pull/1732) with th efollowing [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/be8ab78e-da84-11ec-a628-fa163e4788b2/) and [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/be8ab78e-da84-11ec-a628-fa163e4788b2/report.html):
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pki/server/pkiserver.py", line 41, in <module>
    cli.execute(sys.argv)
  File "/usr/lib/python3.10/site-packages/pki/server/cli/__init__.py", line 143, in execute
    super().execute(args)
  File "/usr/lib/python3.10/site-packages/pki/cli/__init__.py", line 217, in execute
    module.execute(module_args)
  File "/usr/lib/python3.10/site-packages/pki/cli/__init__.py", line 217, in execute
    module.execute(module_args)
  File "/usr/lib/python3.10/site-packages/pki/server/cli/cert.py", line 1218, in execute
    instance.cert_create(cert_id='sslserver', temp_cert=True)
  File "/usr/lib/python3.10/site-packages/pki/server/instance.py", line 812, in cert_create
    subsystem.temp_cert_create(nssdb, tmpdir, cert_tag, serial, new_cert_file)
  File "/usr/lib/python3.10/site-packages/pki/server/subsystem.py", line 886, in temp_cert_create
    rc = nssdb.create_cert(
  File "/usr/lib/python3.10/site-packages/pki/nssdb.py", line 1429, in create_cert
    self.__create_cert(
  File "/usr/lib/python3.10/site-packages/pki/nssdb.py", line 1685, in __create_cert
    self.run(cmd, check=True)
  File "/usr/lib/python3.10/site-packages/pki/nssdb.py", line 234, in run
    logger.debug('Command: %s', ' '.join(cmd))
TypeError: sequence item 13: expected str instance, int found
```

Test scenario:
- install ipa server
- stop chronyd, move the date in the future, so that ServerCert cert-pki-ca is expired
- stop ipa, remove the ca.sslserver.certreq directive from CS.cfg
- start ipa with --ignore-service-failures
- call getcert resubmit in order to create the CSR in certmonger file
- call ipa-cert-fix

`ipa-cert-fix` fails in the step calling `pki-server cert-fix`. The debugger shows that the command is trying to create a temp cert with `instance.cert_create(cert_id='sslserver', temp_cert=True)`. This call doesn't provide any value for `serial`, hence it reaches the line
```
786  	                if serial is None:
787  	                    # If admin doesn't provide a serial number, set the serial to
788  	                    # the same serial number available in the nssdb
789  ->	                    serial = subsystem.get_subsystem_cert(cert_tag)["serial_number"]
```
and the serial returned by this call is an **int** (see https://github.com/dogtagpki/pki/blob/master/base/common/python/pki/nssdb.py#L1935-L1949)

Later on, the code calls 
```
811  	                # Create Temp Cert and write it to new_cert_file
812  ->	                subsystem.temp_cert_create(nssdb, tmpdir, cert_tag, serial, new_cert_file)
```
which fails because it expects a **str** instead of an **int**.

Companion issue on IPA side: https://pagure.io/freeipa/issue/9163

**Comment by flo-renaud** [comment]
@edewata could you have a look?

**Comment by ckelleyRH** [comment]
@flo-renaud - sorry Endi was OOO, I'll add this to the triage list.

**Comment by edewata** [comment]
Yeah, sorry I was on PTO. There's also a bug for this:
https://bugzilla.redhat.com/show_bug.cgi?id=2095197
