### ISSUE TITLE
Documentation about Registration Authority (RA) implementation

### ISSUE THREAD

**Issue by brokoler** [dogtagpki/pki#4194]
Hello,

I want to create a Registration Authority (RA) in Dogtag, which should be used to forward Clients CSRs to a specific CA (Windows CA in my case).

I didn't find a documentation, just a short description about the functionality:
https://github.com/dogtagpki/pki/wiki/Registration-Authority

I this feature still supported and is there some technical documentation about the implementation?

Thanks and best regards

**Comment by ckelleyRH** [comment]
Thanks for your question! @edewata do you know the answer?

**Comment by edewata** [comment]
Hi, I think the old RA subsystem has been dropped since PKI 9 and I don't have much info about it. It's now recommended to use the ACME subsystem or the soon-to-be-available EST subsystem instead.
