### ISSUE TITLE
nssdb.py can attempt to import a certifcate file that does not exist.

### ISSUE THREAD

**Issue by matthewdva** [dogtagpki/pki#4196]
When attempting to import_pkcs7 certificate there is a condition when the an attempt to import a certificate when one does not exist.

When the number of certificates is 0, an attempt is still made to import `cert-1.crt`

**Comment by ckelleyRH** [comment]
Hi, thanks for raising this! What command were you running? `pki pkcs7-cert-import` directly from the command line or something else?

**Comment by matthewdva** [comment]
> Hi, thanks for raising this! What command were you running? `pki pkcs7-cert-import` directly from the command line or something else?

FYI,  This is a duplicate of #4197 .  I supplied a patch for this issue.  The issue arose when I was installing IPA with custom external root certificate, not a externally signed subordinate. The import certificate file only had a single certificate, not a certificate and a separate root.  Looking through the logs, nssdb.py identified that there were `0` certificates were in the chain but continued attempt to import a file that did not exist.

#4197 has been merged so this ticket can close.

**Comment by ckelleyRH** [comment]
Ah, I see! Makes sense, I shall close then thanks :+1:
