### ISSUE TITLE
How to create rpm for dogtag-pki-server-theme?

### ISSUE THREAD

**Issue by lexcorp** [dogtagpki/pki#4218]
The package rpm for pki-server-theme or dogtag-pki-server-theme is not present on any repository or media of Rocky Linux 9

How to create rpm for this package?

On the media DVD and Rocky Linux repositories only show this packages:

http://dl.rockylinux.org/pub/rocky/9/devel/x86_64/os/Packages/p/

pki-acme-11.0.6-2.el9_0.noarch.rpm
pki-base-11.0.6-2.el9_0.noarch.rpm
pki-base-java-11.0.6-2.el9_0.noarch.rpm
pki-ca-11.0.6-2.el9_0.noarch.rpm
pki-jackson-annotations-2.11.4-6.el9.noarch.rpm
pki-jackson-annotations-javadoc-2.11.4-6.el9.noarch.rpm
pki-jackson-core-2.11.4-6.el9.noarch.rpm
pki-jackson-databind-2.11.4-6.el9.noarch.rpm
pki-jackson-jaxrs-json-provider-2.11.4-7.el9.noarch.rpm
pki-jackson-jaxrs-providers-2.11.4-7.el9.noarch.rpm
pki-jackson-jaxrs-providers-datatypes-2.11.4-7.el9.noarch.rpm
pki-jackson-jaxrs-providers-javadoc-2.11.4-7.el9.noarch.rpm
pki-jackson-jaxrs-providers-parent-2.11.4-7.el9.noarch.rpm
pki-jackson-module-jaxb-annotations-2.11.4-8.el9.noarch.rpm
pki-jackson-modules-base-2.11.4-8.el9.noarch.rpm
pki-kra-11.0.6-2.el9_0.noarch.rpm
pki-resteasy-3.0.26-15.el9.noarch.rpm
pki-resteasy-client-3.0.26-15.el9.noarch.rpm
pki-resteasy-core-3.0.26-15.el9.noarch.rpm
pki-resteasy-jackson2-provider-3.0.26-15.el9.noarch.rpm
pki-server-11.0.6-2.el9_0.noarch.rpm
pki-servlet-4.0-api-9.0.43-4.el9.noarch.rpm
pki-servlet-engine-9.0.43-4.el9.noarch.rpm
pki-symkey-11.0.6-2.el9_0.x86_64.rpm

**Comment by ckelleyRH** [comment]
Hi! I have never used Rocky Linux and I do not know who packages PKI for it or how they do it.

I am running Fedora 36; if I use the build script I get the following:
```
./build.sh rpm

<snip build output lines>

+ exit 0
RPM packages:
 /home/ckelley/build/pki/RPMS/dogtag-pki-tps-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-acme-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-base-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/python3-dogtag-pki-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-theme-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-java-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-ca-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-server-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-javadoc-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-kra-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-ocsp-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-tks-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-tests-11.3.0-0.1.alpha1.fc36.noarch.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-tools-debuginfo-11.3.0-0.1.alpha1.fc36.x86_64.rpm
 /home/ckelley/build/pki/RPMS/pki-debugsource-11.3.0-0.1.alpha1.fc36.x86_64.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-tools-11.3.0-0.1.alpha1.fc36.x86_64.rpm
 /home/ckelley/build/pki/RPMS/dogtag-pki-11.3.0-0.1.alpha1.fc36.x86_64.rpm
``` 
...which includes a theme package, you could try this in the first instance?

**Comment by ckelleyRH** [comment]
Closing as stale.
