### ISSUE TITLE
Images do Not Load and Other Questions

### ISSUE THREAD

**Issue by KodakMaciel** [dogtagpki/pki#4557]
Hi!
`**Images do Not Load - Problem**`

I performed the installation correctly following the "Installing CA Interactively", but when opening in the browser the images are not loaded, I have already tried to perform the reinstallation on another server, but the error remains.
![image](https://github.com/dogtagpki/pki/assets/78926817/fc5b9cd9-9c01-418d-abad-617e93cf1065)
----
`**Operating system version**`
AlmaLinux release 9.2 (Turquoise Kodkod)
---
`**Questions**`

1. Is Dogtag compatible with which versions of operating systems?
2. What are the links to the repositories to download the dogtag-pki and 389-ds packages in Alma Linux 9.X? When trying to install normally, it is not found.

**Comment by ckelleyRH** [comment]
Hi!

Themes are not installed by default, you can begin to learn about them from here: https://www.dogtagpki.org/wiki/Theme. To answer your other questions:

> Is Dogtag compatible with which versions of operating systems?

We test that Dogtag will build on all current Fedora releases, as well as CentOS Stream and RHEL. Our CI pipeline runs in Fedora containers and we maintain Dogtag (as pki-core) in both CentOS Stream and RHEL. While we do not test on other distributions it is likely that Dogtag runs on nearly all Linux distros.

 > What are the links to the repositories to download the dogtag-pki and 389-ds packages in Alma Linux 9.X? When trying to install normally, it is not found.

No idea, we are not the packagers for Alma. The RHEL packages are called pki-core and 389-ds-base so presumably the Alma packages also have those names.
