### ISSUE TITLE
Question regarding "soon-to-be-available EST subsystem"

### ISSUE THREAD

**Issue by kelbenj** [dogtagpki/pki#4623]
@edewata , for https://github.com/dogtagpki/pki/issues/4194 you wrote:

> "Hi, I think the old RA subsystem has been dropped since PKI 9 and I don't have much info about it. It's now recommended to use the ACME subsystem or the soon-to-be-available EST subsystem instead."

Do you have any additional information about the ""soon-to-be-available EST subsystem"? I cannot find anything in the Wiki. I am on a team that is deciding between using the ACME subsystem  or waiting until the EST subsystem is available.

Thank you!

**Comment by edewata** [comment]
Hi, we have some info here:
https://github.com/dogtagpki/pki/wiki/EST-Responder

@fmarco76 FYI

**Comment by fmarco76** [comment]
@kelbenj EST subsystem is already available in dogtag and the installation instructions are in the above link provided by @edewata . ACME has been more tested because it was available before but you could try both and decide which one is the best fit for your use-case.

**Comment by kelbenj** [comment]
Thank you @fmarco76 and @edewata!
