### ISSUE TITLE
Intermittent EST test failure

### ISSUE THREAD

**Issue by edewata** [dogtagpki/pki#4683]
The EST test has been failing quite frequently recently:

https://github.com/dogtagpki/pki/actions/runs/8144862709/job/22260185017#step:7:31
```
Add base entry...
  localhost failed | stderr: ldap_bind: Invalid credentials (49)
```

Usually the failure disappears after restarting the test, but this issue should be investigated since it could indicate some kind of reliability issue.

**Comment by fmarco76** [comment]
After the commit https://github.com/dogtagpki/pki/commit/b9c9f86236a059150270a4347b7ab6d1831e6b7b EST CI is working properly
