### ISSUE TITLE
ipa vault-add fails with "Unable to archive key" (@pki/master)

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#4774]
Vault operations are failing if the master is installed with @pki/master

Reproducer:
1. Enable @pki/master and @freeipa/freeipa-master-nightly
2. upgrade all packages with --enablerepo=updates-testing
3. install ipa server with `ipa-server-install --domain ipa.test --realm IPA.TEST --setup-dns --auto-forwarders -a Secret123 -p Secret123 -U --setup-kra`
4. Add a vault with `echo Secret123 | kinit admin; ipa vault-add ci_test_vault_master --password password --type symmetric`

The command fails with:
```
# ipa vault-add ci_test_vault_master --password password --type symmetric
ipa: ERROR: Unable to archive key: Unable to decrypt passphrase: Cipher context finalization failed: (-8190) security library: received bad data.
```

The error can be seen in FreeIPA nightly tests, for instance in PR #[3720](https://github.com/freeipa-pr-ci2/freeipa/pull/3720) with the test `test_vault`: [report.html](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a57c1394-2331-11ef-8edd-fa163ee42d1c/report.html?sort=result), [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a57c1394-2331-11ef-8edd-fa163ee42d1c/).

IPA httd's error log displays:
```
[Wed Jun 05 12:23:48.147804 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490] ipa: ERROR: non-public: HTTPError: 500 Server Error: Internal Server Error for url: https://master.ipa.test:443/kra/rest/agent/keyrequests
[Wed Jun 05 12:23:48.147837 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490] Traceback (most recent call last):
[Wed Jun 05 12:23:48.147840 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]   File "/usr/lib/python3.12/site-packages/requests/models.py", line 971, in json
[Wed Jun 05 12:23:48.147843 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]     return complexjson.loads(self.text, **kwargs)
[Wed Jun 05 12:23:48.147845 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Jun 05 12:23:48.147848 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]   File "/usr/lib64/python3.12/json/__init__.py", line 346, in loads
[Wed Jun 05 12:23:48.147850 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]     return _default_decoder.decode(s)
[Wed Jun 05 12:23:48.147853 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Jun 05 12:23:48.147855 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]   File "/usr/lib64/python3.12/json/decoder.py", line 337, in decode
[Wed Jun 05 12:23:48.147857 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Wed Jun 05 12:23:48.147859 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Jun 05 12:23:48.147862 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]   File "/usr/lib64/python3.12/json/decoder.py", line 355, in raw_decode
[Wed Jun 05 12:23:48.147864 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490]     raise JSONDecodeError("Expecting value", s, err.value) from None
[Wed Jun 05 12:23:48.147866 2024] [wsgi:error] [pid 26206:tid 26633] [remote 192.168.121.221:59490] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Version:
dogtag-pki-server-11.6.0-0.1.alpha1.20240605033809UTC.92d6b505.fc39.noarch
dogtag-jss-5.6.0-0.1.alpha1.20240523101440UTC.0da84f41.fc39.x86_64

**Comment by edewata** [comment]
@flo-renaud Do you see any error in PKI logs? Or is PKI working fine but returning undecryptable data?

**Comment by flo-renaud** [comment]
The issue has been solved, see nightly test PR #[3928](https://github.com/freeipa-pr-ci2/freeipa/pull/3928) with the test `test_vault` [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/eeecd644-5db0-11ef-a4f7-fa163ed415c1/report.html?sort=result)

Started working with dogtag-pki-base-11.6.0-0.1.alpha1.20240622003224UTC.c8d820f9.fc39.noarch
