### ISSUE TITLE
Rest endpoint /ca/rest/certrequests/{id} returns 500

### ISSUE THREAD

**Issue by illegalhex** [dogtagpki/pki#7]
It seems on the 10.3.X branch of code the endpoint /ca/rest/certrequests/{id} will return a 500 error. On the 10.2.x branch, tested on Fedora 23, this call would return the correct response of the cert request with the corresponding id. The error on 10.3.x was observed on Fedora 24,25, and 26 by following the process outlined on http://pki.fedoraproject.org/wiki/Quick_Start.

Is there something missing in the documentation that is needed to make the api call functional like a specific version of a java library and/or tomcat that isn't specified in the dogtag-pki deb?

Link to the http error and the tomcat error output: 
https://gist.github.com/illegalhex/3e5497d18518e58a9c1ecdd49acd0d74

**Comment by mharmsen99** [comment]
This issue has been migrated to the official Dogtag PKI Pagure Issues site:
* https://pagure.io/dogtagpki/issue/2905 - Rest endpoint /ca/rest/certrequests/{id} returns 500
